### ISSUE TITLE
Rename back to `tap-google-analytics-v4`

### ISSUE THREAD

**Issue by tayloramurphy** [MeltanoLabs/tap-ga4#5]
My instinct is that we should have a more descriptive name rather than the abbreviation. What was the motivation behind shortening it @pnadolny13 ?

**Comment by tayloramurphy** [comment]
Nevermind. I think it's fine. THe experience on the Hub is good and google talks about it as GA4. At some point we may want aliases though.

**Comment by pnadolny13** [comment]
@tayloramurphy yeah everyone refers to it as GA4 and the singer-io variant is already labled tap-ga4 so I thought it was clearer to just go with it.

This process makes me wonder how we should migrate between endpoints for taps like this, technically its still tap-google-analytics so we could go another direction where we use the original tap-google-analytics and migrate it to use the GA4 endpoint. Hotglue does a lot of tap-<x>-v1 and tap-<x>-v2 but I wonder if its better to keep tap-<x> that migrates to the latest endpoints. If we take this path then in 6 months or so when the UA google endpoints are turned off then tap-ga4 will be the only tap and tap-google-analytics will need to be archived.
